/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANURUDDHA
 */
public class SupplierPayments extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupplierPayments
     */
    public SupplierPayments() {
        initComponents();
        creditDetails();
    }

    void creditDetails() {
        try {
            DefaultTableModel d = (DefaultTableModel) jTable2.getModel();
            d.setRowCount(0);
//            double invo_amount = 0;
//            double cash_amount = 0;
//            double credit_amount = 0;
//            String invo_no = "";
//            ResultSet rs_cash_amount = JDBC.getdata("select invoice_no,sum(amount) as sum from customer_payments where method='cash' group by invoice_no");
//            ResultSet rs_credit_amount = JDBC.getdata("select invoice_no,sum(amount) as sum from customer_payments where method='credit' group by invoice_no");

            ResultSet rs_credit = JDBC.getdata("SELECT invoice_info.invoice_no, invoice_info.total_amount-Sum(customer_payments.amount) AS balance "
                    + "FROM (customer_payments INNER JOIN invoice_info ON customer_payments.invoice_no=invoice_info.invoice_no) "
                    + "GROUP BY invoice_no "
                    + "HAVING balance>0");

            ResultSet rs_credits = JDBC.getdata("SELECT grn_info.grn_no, grn_info.total_amount-Sum(supplier_payments.amount) AS balance "
                    + "FROM (supplier_payments INNER JOIN grn_info ON supplier_payments.grn_no=grn_info.grn_no) "
                    + "GROUP BY grn_no "
                    + "HAVING balance>0");

            while (rs_credits.next()) {
                Vector v = new Vector();
                v.add(rs_credits.getString("grn_no"));
                v.add(rs_credits.getString("balance"));
                d.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Supplier Payments");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Amount"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("View Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            DefaultTableModel d = (DefaultTableModel) jTable2.getModel();
            if (d.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No records available", "Input eror", JOptionPane.ERROR_MESSAGE);
            } else {
                double correct_amount = 0;
                String spamount = JOptionPane.showInputDialog(null, "Enter amount", "");
                if (spamount.equals(null)) {
                    JOptionPane.showMessageDialog(null, "Enter amount in correct format", "Input eror", JOptionPane.ERROR_MESSAGE);
                } else {
                    double dpmaount = Double.parseDouble(spamount);
                    double amount = Double.parseDouble(d.getValueAt(jTable2.getSelectedRow(), 1).toString());

                    if (dpmaount < amount) {
                        correct_amount = dpmaount;
                    } else {
                        correct_amount = amount;
                    }

                    String ino = d.getValueAt(jTable2.getSelectedRow(), 0).toString();

                    String cash_account = "DSKH15000001";
                    ResultSet rs_grn_info = JDBC.getdata("SELECT * FROM grn_info WHERE grn_no='" + ino + "'");
                    String sid = "";
                    while (rs_grn_info.next()) {
                        sid = rs_grn_info.getString("sid");
                    }

                    //pay credits
                    Account.debit(sid, ino, correct_amount, QuickDateTime.date());
                    Account.credit(cash_account, ino, correct_amount, QuickDateTime.date());                    

                    //                    ResultSet rs_customer_payment = JDBC.getdata("SELECT * FROM customer_payments WHERE invoice_no='" + ino + "'");
                    //                    String id = "";
                    //                    while (rs_customer_payment.next()) {
                    //                        cid = rs_invoice_info.getString("cid");
                    //                    }

                    JDBC.putdata("INSERT INTO supplier_payments VALUES(0,'" + ino + "','" + correct_amount + "','Cash')");
                    creditDetails();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter amount in correct format", "Input eror", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            //            JOptionPane.showMessageDialog(null, "Enter a amount", "Input eror", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(CustomerPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
